### ISSUE TITLE
please upgrade to core-elements 4

### ISSUE THREAD

**Issue by Andersmholmgren** [bwu-dart/bwu_fontawesome_iconset_svg#3]
Not sure if there is any breaking changes that would impact it. Also 5 is likely coming soon given it's recent release in js so you may want to hold off until that lands in dart

**Comment by Andersmholmgren** [comment]
poke ;-P

**Comment by zoechi** [comment]
@Andersmholmgren sorry for the delay. 
Just published an updated version.
