### ISSUE TITLE
add note to readme that things will go spectacularly wrong if you don't have <meta charset="utf-8">

### ISSUE THREAD

**Issue by Andersmholmgren** [bwu-dart/bwu_fontawesome_iconset_svg#4]
If you leave out the `<meta charset="utf-8">` in the header then the displayed icon is completely wrong. This is not at all obvious so worth making a big noise about in the readme

**Comment by zoechi** [comment]
Interesting. Did you also try https://www.polymer-project.org/docs/elements/icons.html with `charset="utf-8"`?

**Comment by zoechi** [comment]
Thanks for the report!
Hmm, there are only 4 simple steps in the `Usage` section in the `Readme.md` where `<meta charset="utf-8">` is the first. 
I added an additional comment. I hope this makes it more clear.
